# Microplastic Toxicity Levels and Their Respective Human Biological Effects

### This is a predictive model to assess whether microplastic characteristics
### (polymer type, shape, particle length, and size category) could be used to predict toxic effects.
### RESULTS: Limited predictive power (AUC ≈ 0.840), suggesting that additional factors such as
### surface chemistry, and exposure time are likely important drivers of toxicity.

## Package Import and Data Reading/Cleaning

In [37]:
# Import necessary packages for data cleaning

import pandas as pd
import seaborn as sns
from IPython.display import display
import matplotlib.pyplot as plt
import numpy as np
#!pip install shap # may need to download this package as it's not built-in #

In [38]:
# Numpy may need to be downgraded for feature compatability 
#!pip install "numpy<=2.1" --force-reinstall

print("Numpy version:", np.__version__)

Numpy version: 2.1.0

In [39]:
# Read in data

file_path = "particle_data.csv"
df = pd.read_csv(file_path)

display(df)

,source,DOI,Authors,Year,Species,Life Stage,In vitro/in vivo,Sex,Experiment Type,Exposure Route,...,Sodium Azide Present?,Screened for Chemical Contamination?,Particle Cleaning?,Solvent Rinse,Background Contamination Monitored?,Concentration Validated?,Particle Behavior,Uptake Validated?,Tissue Distribution,Organisms Fed?
0,search,10.1007/s12013-015-0705-6,Barshtein,2016,(Human) Homo sapiens,Not Reported,In Vitro,NaN,Particle Only,In Vitro,...,unknown,N,not_cleaned,none,N,N,not_evaluated,No,NaN,NaN
1,search,10.1007/s12013-015-0705-6,Barshtein,2016,(Human) Homo sapiens,Not Reported,In Vitro,NaN,Particle Only,In Vitro,...,unknown,N,not_cleaned,none,N,N,not_evaluated,No,NaN,NaN
2,search,10.1007/s12013-015-0705-6,Barshtein,2016,(Human) Homo sapiens,Not Reported,In Vitro,NaN,Particle Only,In Vitro,...,unknown,N,not_cleaned,none,N,N,not_evaluated,No,NaN,NaN
3,search,10.1007/s12013-015-0705-6,Barshtein,2016,(Human) Homo sapiens,Not Reported,In Vitro,NaN,Particle Only,In Vitro,...,unknown,N,not_cleaned,none,N,N,not_evaluated,No,NaN,NaN
4,search,10.1007/s12013-015-0705-6,Barshtein,2016,(Human) Homo sapiens,Not Reported,In Vitro,NaN,Particle Only,In Vitro,...,unknown,N,not_cleaned,none,N,N,not_evaluated,No,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1103,workshop,10.1016/j.jhazmat.2020.123933,Li,2021,(Human) Homo sapiens,Not Reported,In Vitro,NaN,Particle Only,In Vitro,...,unknown,N,not_cleaned,none,N,N,not_evaluated,Yes,liver,Y
1104,workshop,10.1016/j.jhazmat.2020.123933,Li,2021,(Human) Homo sapiens,Not Reported,In Vitro,NaN,Particle Only,In Vitro,...,unknown,N,not_cleaned,none,N,N,not_evaluated,Yes,liver,Y
1105,workshop,10.1016/j.jhazmat.2020.123933,Li,2021,(Human) Homo sapiens,Not Reported,In Vitro,NaN,Particle Only,In Vitro,...,unknown,N,not_cleaned,none,N,N,not_evaluated,Yes,liver,Y
1106,workshop,10.1016/j.jhazmat.2020.123933,Li,2021,(Human) Homo sapiens,Not Reported,In Vitro,NaN,Particle Only,In Vitro,...,unknown,N,not_cleaned,none,N,N,not_evaluated,Yes,liver,Y
1107,workshop,10.1016/j.jhazmat.2020.123933,Li,2021,(Human) Homo sapiens,Not Reported,In Vitro,NaN,Particle Only,In Vitro,...,unknown,N,not_cleaned,none,N,N,not_evaluated,Yes,liver,Y

## Exploratory Data Analysis

In [40]:
df["Exposure Media"].unique()

array(['phosphate buffer saline', 'culture medium DMEM', 'LHC-9 medium',
       'culture medium DMEMF12', 'culture media', 'blood', 'serum',
       'RPMI 1610 medium', 'culture medium',
       'dulbecco modified eagle medium', 'DMEM high glucose',
       'endothelial medium', 'HamsF12', 'MEM',
       'dulbecco modified eagle medium F-12', 'EBM2', 'DMEM', 'DMEM egf',
       'DMEM medium', 'human serum', 'pig serum',
       'eagles minimal essential medium', 'culture medium 106',
       'dulbecco modified eagle media', 'phenol red free medium',
       'eagles minimum essential medium', 'bronchoalveolar lavage fluid',
       'minimum essential media', 'bronchial epithelial growth medium',
       'MCDB131 medium', 'eagle minimal essential medium',
       'roswell park memorial institute serum-free medium',
       'serum-free culture medium',
       'roswell park memorial institute 1640 medium', 'rpmi1640 medium'],
      dtype=object)

In [41]:
df.columns.unique()

Index(['source', 'DOI', 'Authors', 'Year', 'Species', 'Life Stage',
       'In vitro/in vivo', 'Sex', 'Experiment Type', 'Exposure Route',
       'Particle Mix?', 'Negative Control', 'Reference Particle',
       'Exposure Media', 'Solvent', 'Detergent', 'pH', 'Salinity (ppt)',
       'Temperature (Avg)', 'Temperature (Min)', 'Temperature (Max)',
       'Exposure Duration (days)', 'Number of Doses', 'Replicates',
       'Sample Size', 'Dosing Frequency', 'Nominal Chemical Added',
       'Nominal Chemical Added Dose', 'Nominal Chemical Added Dose Units',
       'Measured Chemical Added', 'Measured Chemical Added Dose',
       'Measured Chemical Added Dose Units', 'Selected Dose', 'Effect',
       'Direction', 'Broad Endpoint Category', 'Specific Endpoint Category',
       'Endpoint', 'Level of Biological Organization',
       'Target Organelle, Cell, or Tissue', 'Polymer', 'Shape',
       'Density (g/cm^3)', 'Density, reported or estimated', 'Charge',
       'Zeta Potential (mV)', 'Zeta Potential Media', 'Functional Group',
       'Particle Length (μm)', 'Size Category', 'Particle Volume (μm^3)',
       'Particle Mass (mg)', 'Weathered or Biofouled?', 'Size Validated?',
       'Polymer Validated?', 'Shape Validated', 'Particle Source',
       'Sodium Azide Present?', 'Screened for Chemical Contamination?',
       'Particle Cleaning?', 'Solvent Rinse',
       'Background Contamination Monitored?', 'Concentration Validated?',
       'Particle Behavior', 'Uptake Validated?', 'Tissue Distribution',
       'Organisms Fed?'],
      dtype='object')

In [42]:
df["Size Category"].unique()

array(['100nm < 1µm', '1µm < 100µm', 'Not Reported', '1nm < 100nm',
       '100µm < 1mm'], dtype=object)

In [43]:
df["Direction"].unique()

array(['Increase', nan, 'Decrease', 'Na'], dtype=object)

In [44]:
df["Zeta Potential (mV)"].unique()

array([   nan,  -9.8 , -26.8 , -36.  ,  54.  , -58.2 , -36.1 , -23.6 ,
         3.7 ,   4.2 , -23.7 ,   5.6 , -21.9 , -36.05, -44.55, -36.25,
       -19.73, -17.07, -11.5 ,  16.05, -37.57, -37.07])

In [45]:
df["Density (g/cm^3)"].unique()

array([1.07 , 1.34 , 0.875, 1.09 , 1.14 ,   nan, 1.15 , 1.19 , 0.95 ,
       0.935, 1.05 ])

In [46]:
df['Broad Endpoint Category'].unique()

array(['Circulatory', 'Stress', 'Immune', 'Cytotoxicity', 'Metabolism',
       'Respiratory', 'Cell Morphology and Structure',
       'Cell Growth and Proliferation', 'Alimentary, Excretory'],
      dtype=object)

In [47]:
df.columns.unique()

Index(['source', 'DOI', 'Authors', 'Year', 'Species', 'Life Stage',
       'In vitro/in vivo', 'Sex', 'Experiment Type', 'Exposure Route',
       'Particle Mix?', 'Negative Control', 'Reference Particle',
       'Exposure Media', 'Solvent', 'Detergent', 'pH', 'Salinity (ppt)',
       'Temperature (Avg)', 'Temperature (Min)', 'Temperature (Max)',
       'Exposure Duration (days)', 'Number of Doses', 'Replicates',
       'Sample Size', 'Dosing Frequency', 'Nominal Chemical Added',
       'Nominal Chemical Added Dose', 'Nominal Chemical Added Dose Units',
       'Measured Chemical Added', 'Measured Chemical Added Dose',
       'Measured Chemical Added Dose Units', 'Selected Dose', 'Effect',
       'Direction', 'Broad Endpoint Category', 'Specific Endpoint Category',
       'Endpoint', 'Level of Biological Organization',
       'Target Organelle, Cell, or Tissue', 'Polymer', 'Shape',
       'Density (g/cm^3)', 'Density, reported or estimated', 'Charge',
       'Zeta Potential (mV)', 'Zeta Potential Media', 'Functional Group',
       'Particle Length (μm)', 'Size Category', 'Particle Volume (μm^3)',
       'Particle Mass (mg)', 'Weathered or Biofouled?', 'Size Validated?',
       'Polymer Validated?', 'Shape Validated', 'Particle Source',
       'Sodium Azide Present?', 'Screened for Chemical Contamination?',
       'Particle Cleaning?', 'Solvent Rinse',
       'Background Contamination Monitored?', 'Concentration Validated?',
       'Particle Behavior', 'Uptake Validated?', 'Tissue Distribution',
       'Organisms Fed?'],
      dtype='object')

In [48]:
df["Endpoint"].unique()

array(['Cell Aggregate Size', 'Cell Aggregation (Small)', 'Cell Adhesion',
       'Micronuclei Frequency', 'hsp70 mRNA expression',
       'IL1b mRNA expression', 'Cytotoxicity', 'IL8 mRNA expression',
       'DNA damage', 'gstp1 mRNA expression', 'ho1 mRNA expression',
       'Mitochondrial Membrane Potential', 'Mitochondria ROS Production',
       'Reactive Oxygen Species Production', 'sod2 mRNA expression',
       'zo1 protein expression', 'Transepithelial Electric Resistance',
       'aat protein expression', 'IL6 protein expression',
       'IL8 protein expression', 'ho1 protein expression',
       'Lyosomal Protonation', 'CD163 protein expression',
       'CD200R protein expression', 'CD86 protein expression',
       'IL10 Release', 'IL1b Release', 'ATP Concentration', 'NADH Levels',
       'nos2 protein expression', 'Phagocytosis',
       'Immune Cell Proliferation', 'Immune Cell Protein Concentration',
       'tgfb1 Release', 'TNFa Release', 'Number of Mitochondria',
       'CD11b protein expression', 'CD14 protein expression',
       'CD45 protein expression', 'CD61 protein expression',
       'Leukocyte Adhesion', 'tf protein expression', 'Annexin V Binding',
       'iC3b Concentration', 'sc5b9 Concentration', 'IL1a Release',
       'Annexin V', 'Monocyte Adhesion', 'Glutathione Concentration',
       'Malondialdehyde Concentration', 'SOD Activity',
       'p53 protein expression', 'Cell Membrane Damage',
       'Histone Acetylation', 'Nuclear Intensity', 'Nuclear Size',
       'Caspase 3 Activity', 'Cell Cycle G0G1 Phase',
       'Cell Cycle G2M Phase', 'Cell Cycle S Phase',
       'Cell Cycle Sub G0G1 Phase', 'Proliferation', 'IL8 Release',
       'Lactate Dehydrogenase Release', 'Cell Cycle',
       'Cylin D protein expression', 'cyclin e protein expression',
       'Complement Activation Bb', 'Complement Activation C3a',
       'Complement Activation C4d', 'Complement Activation sc5b9',
       'ccl22 mRNA expression', 'CD 206 mRNA expression',
       'CD209 mRNA expression', 'cxc10 mRNA expression',
       'stat1 Phosphorylation', 'stat6 Phosphorylation',
       'CDK4 mRNA expression', 'cyclin d1 mRNA expression',
       'iNOS mRNA expression', 'Catalase Activity', 'mek mRNA expression',
       'erk mRNA expression', 'ras mRNA expression',
       'trpv1 mRNA expression', 'Caspase Activation',
       'Intracellular Calcium Levels', 'Lysosomal Integrity',
       'ccnd1 mRNA expression', 'ccne1 mRNA expression',
       'cmyc mRNA expression', 'IL6 mRNA expression',
       'nfkb1 mRNA expression', 'erk1 mRNA expression',
       'p38 mRNA expression', 'ki67 mRNA expression',
       'Nucleus Cytoplasm Ratio', 'p53 mRNA expression',
       'tgfb1 mRNA expression', 'Apoptosis', 'BAX protein expression',
       'Caspase 3 protein expression', 'Caspase 8 protein expression',
       'Caspase 9 protein expression', 'ccnd mRNA expression',
       'ccne mRNA expression', 'il1 mRNA expression',
       'cyclin d3 protein expression',
       'Nuclear factor kB (NFkB) mRNA expression',
       'dr5 protein expression', 'p70s6k protein expression',
       'tnfa mRNA expression', 'Cytochrome C protein expression',
       'Cell Morphology', 'IL6 Release', 'Hemolysis',
       'nrf2 protein expression', 'keap1 protein expression',
       'nqo1 protein expression'], dtype=object)

In [49]:
df['Broad Endpoint Category'].value_counts()

Broad Endpoint Category
Cytotoxicity                     382
Immune                           302
Metabolism                       178
Cell Growth and Proliferation    121
Stress                            57
Cell Morphology and Structure     40
Circulatory                       15
Alimentary, Excretory              9
Respiratory                        4
Name: count, dtype: int64

In [50]:
df["Charge"].unique()

array([nan, 'negative', 'positive'], dtype=object)

In [51]:
df["Zeta Potential (mV)"].value_counts()

Zeta Potential (mV)
-9.80     55
-36.00    46
 54.00    46
-36.10    41
 16.05    30
-58.20    20
-26.80    18
-37.57    16
-37.07    16
-23.70    13
-23.60    13
 3.70     13
 4.20     13
 5.60     13
-21.90    13
-36.05     4
-44.55     4
-17.07     4
-19.73     4
-36.25     4
-11.50     4
Name: count, dtype: int64

In [52]:
df["Endpoint"].unique()

array(['Cell Aggregate Size', 'Cell Aggregation (Small)', 'Cell Adhesion',
       'Micronuclei Frequency', 'hsp70 mRNA expression',
       'IL1b mRNA expression', 'Cytotoxicity', 'IL8 mRNA expression',
       'DNA damage', 'gstp1 mRNA expression', 'ho1 mRNA expression',
       'Mitochondrial Membrane Potential', 'Mitochondria ROS Production',
       'Reactive Oxygen Species Production', 'sod2 mRNA expression',
       'zo1 protein expression', 'Transepithelial Electric Resistance',
       'aat protein expression', 'IL6 protein expression',
       'IL8 protein expression', 'ho1 protein expression',
       'Lyosomal Protonation', 'CD163 protein expression',
       'CD200R protein expression', 'CD86 protein expression',
       'IL10 Release', 'IL1b Release', 'ATP Concentration', 'NADH Levels',
       'nos2 protein expression', 'Phagocytosis',
       'Immune Cell Proliferation', 'Immune Cell Protein Concentration',
       'tgfb1 Release', 'TNFa Release', 'Number of Mitochondria',
       'CD11b protein expression', 'CD14 protein expression',
       'CD45 protein expression', 'CD61 protein expression',
       'Leukocyte Adhesion', 'tf protein expression', 'Annexin V Binding',
       'iC3b Concentration', 'sc5b9 Concentration', 'IL1a Release',
       'Annexin V', 'Monocyte Adhesion', 'Glutathione Concentration',
       'Malondialdehyde Concentration', 'SOD Activity',
       'p53 protein expression', 'Cell Membrane Damage',
       'Histone Acetylation', 'Nuclear Intensity', 'Nuclear Size',
       'Caspase 3 Activity', 'Cell Cycle G0G1 Phase',
       'Cell Cycle G2M Phase', 'Cell Cycle S Phase',
       'Cell Cycle Sub G0G1 Phase', 'Proliferation', 'IL8 Release',
       'Lactate Dehydrogenase Release', 'Cell Cycle',
       'Cylin D protein expression', 'cyclin e protein expression',
       'Complement Activation Bb', 'Complement Activation C3a',
       'Complement Activation C4d', 'Complement Activation sc5b9',
       'ccl22 mRNA expression', 'CD 206 mRNA expression',
       'CD209 mRNA expression', 'cxc10 mRNA expression',
       'stat1 Phosphorylation', 'stat6 Phosphorylation',
       'CDK4 mRNA expression', 'cyclin d1 mRNA expression',
       'iNOS mRNA expression', 'Catalase Activity', 'mek mRNA expression',
       'erk mRNA expression', 'ras mRNA expression',
       'trpv1 mRNA expression', 'Caspase Activation',
       'Intracellular Calcium Levels', 'Lysosomal Integrity',
       'ccnd1 mRNA expression', 'ccne1 mRNA expression',
       'cmyc mRNA expression', 'IL6 mRNA expression',
       'nfkb1 mRNA expression', 'erk1 mRNA expression',
       'p38 mRNA expression', 'ki67 mRNA expression',
       'Nucleus Cytoplasm Ratio', 'p53 mRNA expression',
       'tgfb1 mRNA expression', 'Apoptosis', 'BAX protein expression',
       'Caspase 3 protein expression', 'Caspase 8 protein expression',
       'Caspase 9 protein expression', 'ccnd mRNA expression',
       'ccne mRNA expression', 'il1 mRNA expression',
       'cyclin d3 protein expression',
       'Nuclear factor kB (NFkB) mRNA expression',
       'dr5 protein expression', 'p70s6k protein expression',
       'tnfa mRNA expression', 'Cytochrome C protein expression',
       'Cell Morphology', 'IL6 Release', 'Hemolysis',
       'nrf2 protein expression', 'keap1 protein expression',
       'nqo1 protein expression'], dtype=object)

In [53]:
df["Particle Length (μm)"].unique()

array([1.46450e-01, 2.10855e-01, 4.06000e+00, 1.00000e-01, 1.17000e-01,
       1.19000e-01, 4.50000e-01,         nan, 1.00000e+00, 3.00000e+00,
       5.00000e-02, 4.63000e-02, 4.65800e-01, 1.35000e+01, 1.15000e+02,
       5.00200e+00, 7.60000e+01, 1.55000e+02, 2.72000e+02, 2.92000e+02,
       3.06000e+02, 5.71400e-02, 6.14500e-02, 9.93300e-02, 1.24400e-01,
       4.50200e-01, 4.65300e-01, 1.94300e-01, 5.45100e-01, 7.91000e-01,
       1.50000e-01, 5.02000e+00, 8.05000e+00, 1.05000e+00, 3.99000e+00,
       9.78000e+00, 8.50000e-01, 8.60000e-01, 8.80000e-01, 5.31000e-02,
       5.61000e-02, 6.52700e-02, 7.80000e-02, 7.86500e-02, 8.80800e-02,
       1.60000e-01, 5.00000e+00, 2.39000e-01, 5.45500e-02, 8.72300e-02,
       1.50000e-02, 2.50000e-02, 7.00000e-02, 1.50000e+01, 5.00000e+01,
       1.37500e+02, 4.98000e+00])

In [54]:
df["Endpoint"].value_counts()

Endpoint
Cytotoxicity                          382
Reactive Oxygen Species Production     69
Cell Cycle                             26
Cell Membrane Damage                   24
tf protein expression                  21
                                     ...
Cell Cycle S Phase                      1
Caspase 3 Activity                      1
Cell Cycle G2M Phase                    1
Cell Cycle G0G1 Phase                   1
Cell Morphology                         1
Name: count, Length: 119, dtype: int64

## Data Cleaning:
## Columns needed for Exposure Prediction
### 'Endpoint' = Precise variable being measured or outcome being tracked
### 'Shape' = Shape of polymer used each experiment 
### 'Polymer' =  Polymer type for each experiment
### 'Size Category' = Categorized size of each polymer/experiment

## Target variable
### 'Cytotoxicity' = Does the exposure invoke cytotoxic effects on the targeted endpoint/organelle

In [55]:
target_columns = ['Shape', 'Polymer', 'Zeta Potential (mV)', 'Size Category', 'Broad Endpoint Category'] #  'Selected Dose'
ndf = df[target_columns]

In [56]:
ndf = ndf.dropna()
ndf = ndf[ndf["Size Category"] != 'Not Reported']
print(ndf)

      Shape      Polymer  Zeta Potential (mV) Size Category  \
6    Sphere  Polystyrene                -9.80   100nm < 1µm
7    Sphere  Polystyrene                -9.80   100nm < 1µm
8    Sphere  Polystyrene                -9.80   100nm < 1µm
9    Sphere  Polystyrene                -9.80   100nm < 1µm
10   Sphere  Polystyrene                -9.80   100nm < 1µm
..      ...          ...                  ...           ...
941  Sphere  Polystyrene               -37.07   1nm < 100nm
942  Sphere  Polystyrene               -37.07   1nm < 100nm
943  Sphere  Polystyrene               -37.07   1nm < 100nm
944  Sphere  Polystyrene               -37.07   1nm < 100nm
945  Sphere  Polystyrene               -37.07   1nm < 100nm

           Broad Endpoint Category
6                           Stress
7                           Stress
8                           Stress
9                           Stress
10                          Stress
..                             ...
941                         Stress
942  Cell Growth and Proliferation
943  Cell Morphology and Structure
944  Cell Growth and Proliferation
945                         Immune

[390 rows x 5 columns]

In [57]:
# # Change effect to 1 (True) and 0 (False)

# ndf["Effect"] = ndf["Effect"].map({"Yes": 1, "No": 0})

In [58]:
ndf["Shape"].unique()

array(['Sphere', 'Not Reported'], dtype=object)

In [59]:
# Dropping 'Not Reported' as it could interfere with model accuracy

ndf = ndf[ndf["Shape"] != "Not Reported"]

ndf["Shape"].unique()

array(['Sphere'], dtype=object)

In [60]:
display(ndf)
ndf.value_counts()

,Shape,Polymer,Zeta Potential (mV),Size Category,Broad Endpoint Category
6,Sphere,Polystyrene,-9.80,100nm < 1µm,Stress
7,Sphere,Polystyrene,-9.80,100nm < 1µm,Stress
8,Sphere,Polystyrene,-9.80,100nm < 1µm,Stress
9,Sphere,Polystyrene,-9.80,100nm < 1µm,Stress
10,Sphere,Polystyrene,-9.80,100nm < 1µm,Stress
...,...,...,...,...,...
941,Sphere,Polystyrene,-37.07,1nm < 100nm,Stress
942,Sphere,Polystyrene,-37.07,1nm < 100nm,Cell Growth and Proliferation
943,Sphere,Polystyrene,-37.07,1nm < 100nm,Cell Morphology and Structure
944,Sphere,Polystyrene,-37.07,1nm < 100nm,Cell Growth and Proliferation
945,Sphere,Polystyrene,-37.07,1nm < 100nm,Immune

Shape   Polymer      Zeta Potential (mV)  Size Category  Broad Endpoint Category
Sphere  Polystyrene  -36.10               100nm < 1µm    Cytotoxicity                     23
                     -9.80                100nm < 1µm    Metabolism                       20
                                                         Stress                           20
                      16.05               100nm < 1µm    Cytotoxicity                     19
                     -58.20               1nm < 100nm    Cytotoxicity                     16
                     -36.10               100nm < 1µm    Stress                            9
                     -23.70               100nm < 1µm    Cell Growth and Proliferation     8
                     -21.90               100nm < 1µm    Cell Growth and Proliferation     8
                     -9.80                100nm < 1µm    Immune                            8
                     -23.60               1nm < 100nm    Cell Growth and Proliferation     8
                      3.70                1nm < 100nm    Cell Growth and Proliferation     8
                      5.60                100nm < 1µm    Cell Growth and Proliferation     8
                      4.20                1nm < 100nm    Cell Growth and Proliferation     8
                     -36.10               100nm < 1µm    Cell Growth and Proliferation     7
                     -9.80                100nm < 1µm    Cytotoxicity                      7
                      16.05               100nm < 1µm    Stress                            6
                     -37.07               1nm < 100nm    Cell Growth and Proliferation     6
                     -37.57               1nm < 100nm    Cell Growth and Proliferation     6
                     -26.80               1µm < 100µm    Immune                            6
                     -37.07               1nm < 100nm    Immune                            5
                     -37.57               1nm < 100nm    Immune                            5
                     -26.80               1µm < 100µm    Cytotoxicity                      4
                     -36.25               100nm < 1µm    Immune                            4
                      4.20                1nm < 100nm    Cytotoxicity                      4
                      5.60                100nm < 1µm    Cytotoxicity                      4
                     -19.73               1nm < 100nm    Cytotoxicity                      4
                      3.70                1nm < 100nm    Cytotoxicity                      4
                     -21.90               100nm < 1µm    Cytotoxicity                      4
                     -17.07               1nm < 100nm    Cytotoxicity                      4
                     -23.70               100nm < 1µm    Cytotoxicity                      4
                     -26.80               1µm < 100µm    Respiratory                       4
                     -11.50               1nm < 100nm    Cytotoxicity                      4
                     -23.60               1nm < 100nm    Cytotoxicity                      4
                     -36.05               100nm < 1µm    Immune                            4
                     -44.55               100nm < 1µm    Immune                            4
                     -37.57               1nm < 100nm    Cytotoxicity                      3
                     -37.07               1nm < 100nm    Cytotoxicity                      3
                     -58.20               1nm < 100nm    Stress                            2
                     -26.80               1µm < 100µm    Metabolism                        2
                      16.05               100nm < 1µm    Metabolism                        2
                     -58.20               1nm < 100nm    Alimentary, Excretory             2
                      16.05               100nm < 1µm    Cell Morphology and Structure     2
                     -26.80               1µm < 100µm    Stress                            2
                     -36.10               100nm < 1µm    Alimentary, Excretory             2
                     -37.57               1nm < 100nm    Stress                            1
                     -37.07               1nm < 100nm    Stress                            1
                     -37.57               1nm < 100nm    Cell Morphology and Structure     1
                     -37.07               1nm < 100nm    Cell Morphology and Structure     1
                     -21.90               100nm < 1µm    Metabolism                        1
                     -23.70               100nm < 1µm    Metabolism                        1
                     -23.60               1nm < 100nm    Metabolism                        1
                      4.20                1nm < 100nm    Metabolism                        1
                      3.70                1nm < 100nm    Metabolism                        1
                      16.05               100nm < 1µm    Cell Growth and Proliferation     1
                      5.60                100nm < 1µm    Metabolism                        1
Name: count, dtype: int64

In [61]:
ndf.Polymer.unique()

array(['Polystyrene'], dtype=object)

In [62]:
ndf.Polymer.value_counts()

Polymer
Polystyrene    298
Name: count, dtype: int64

In [63]:
#ndf["Selected Dose"].describe()

In [64]:
# Dropping Polymer types with low counts of data points as it could interfere with model predictions

drop_values = ['Polyethylene','Polyamide','Polyurathane','Tire Rubber','Polyvinylchloride']
ndf = ndf[~ndf["Polymer"].isin(drop_values)]

ndf.Polymer.value_counts()

Polymer
Polystyrene    298
Name: count, dtype: int64

# Machine Learning

In [65]:
# Assigning X and y variables for model

tdf = ndf.copy()

X = tdf.drop(columns = ["Broad Endpoint Category"])
y = tdf.pop("Broad Endpoint Category")

In [ ]:
# encoding y values before splitting as the pipeline doesn't allow for target variable encoding

In [66]:
# Required package for training/test data 

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [67]:
X_train.columns

Index(['Shape', 'Polymer', 'Zeta Potential (mV)', 'Size Category'], dtype='object')

In [68]:
display(X_train)

      Shape      Polymer  Zeta Potential (mV) Size Category
606  Sphere  Polystyrene               -36.25   100nm < 1µm
74   Sphere  Polystyrene               -26.80   1µm < 100µm
604  Sphere  Polystyrene               -36.25   100nm < 1µm
43   Sphere  Polystyrene                -9.80   100nm < 1µm
22   Sphere  Polystyrene                -9.80   100nm < 1µm
..      ...          ...                  ...           ...
571  Sphere  Polystyrene                 5.60   100nm < 1µm
77   Sphere  Polystyrene               -26.80   1µm < 100µm
377  Sphere  Polystyrene               -36.10   100nm < 1µm
918  Sphere  Polystyrene               -37.57   1nm < 100nm
373  Sphere  Polystyrene               -36.10   100nm < 1µm

[208 rows x 4 columns]

In [69]:
display(y_train)

606                           Immune
74                            Immune
604                           Immune
43                            Stress
22                      Cytotoxicity
                   ...
571    Cell Growth and Proliferation
77                        Metabolism
377                     Cytotoxicity
918                           Immune
373                     Cytotoxicity
Name: Broad Endpoint Category, Length: 208, dtype: object

In [70]:
display(y_test)

542                       Metabolism
912    Cell Morphology and Structure
902                     Cytotoxicity
15                            Immune
348                     Cytotoxicity
                   ...
403            Alimentary, Excretory
78                        Metabolism
21                      Cytotoxicity
16                            Immune
540                     Cytotoxicity
Name: Broad Endpoint Category, Length: 90, dtype: object

In [71]:
# Not used in current Pipeline
# Normal FunctionTransformer don't hold feature names
# Created this function to change that

# Required package for function
from sklearn.preprocessing import FunctionTransformer

class NamedFunctionTransformer(FunctionTransformer):
    """
    FunctionTransformer that keeps track of feature names
    for compatibility with ColumnTransformer.get_feature_names_out().
    Makes for better organization.
    """
    def __init__(self, func=None, feature_names=None, **kwargs):
        super().__init__(func=func, **kwargs)
        self._feature_names = feature_names
        self.feature_names = feature_names

    def get_feature_names_out(self, input_features=None):
        # Return given names or fall back to input feature names
        if self._feature_names is not None:
            return np.array(self._feature_names)
        elif input_features is not None:
            return np.array(input_features)
        else:
            raise ValueError("No feature names provided.")

## Logistic Regression Pipeline

In [72]:
# Required Packages for Model

from imblearn.pipeline import Pipeline 
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression 
import numpy as np
from sklearn.calibration import CalibratedClassifierCV


cat_transformer = OneHotEncoder(handle_unknown = "ignore", sparse_output = False)
cat_list = ["Shape", "Polymer", "Size Category"]


num_transformer = StandardScaler()

gb_model = GradientBoostingClassifier(
    n_estimators=1000,
    max_depth=5,
    learning_rate=0.1,
    loss = 'log_loss',
    random_state=42
)


preprocessor = ColumnTransformer(
    transformers = [
        ("cat", cat_transformer, cat_list),
        ("num", num_transformer, ["Zeta Potential (mV)"])
    ]
)

pipe = Pipeline(steps = [
    ("preprocess", preprocessor),
    ("smote", SMOTE(random_state = 42)),
    ("model", gb_model)
    ]
)

In [73]:
# Required packages for model evaluation

from sklearn.metrics import classification_report, confusion_matrix
import shap

pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)  

print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

ValueError: A given column is not a column of the dataframe

In [ ]:
X_train.columns

In [ ]:
f, ax = plt.subplots(figsize=(11, 9))
zdf = tdf.copy()
zdf["Shape"] = zdf["Shape"].map({"Sphere": 1, "Fragment": 0})
zdf["Polymer"] = zdf["Polymer"].map({"Polystyrene": 1, "Polypropylene": 0})

scaler = StandardScaler()
encoder = LabelEncoder()
zdf["Size Category"] = encoder.fit_transform(zdf["Size Category"])
zdf["Endpoint"] = encoder.fit_transform(zdf["Endpoint"])
zdf_num = np.array(zdf["Particle Length (μm)"])
zdf_num = scaler.fit_transform(zdf_num.reshape(-1,1))
zdf["Particle Length (μm)"] = zdf_num

print(zdf)

corr = zdf.corr()

sns.heatmap(corr,  cmap='coolwarm')
plt.show()

In [ ]:
from sklearn.metrics import roc_curve, roc_auc_score
lr_probs = pipe.predict_proba(X_test)[:, 1] 
fpr, tpr, _ = roc_curve(y_test, lr_probs)
auc = roc_auc_score(y_test, lr_probs)

In [ ]:
plt.plot(fpr, tpr, marker='.', label=f'Logistic (AUC = {auc:.3f})')
plt.plot([0, 1], [0, 1], linestyle='--', color='gray', label='Base')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve for Logistic Regression Model')
plt.legend()
plt.grid(True)
plt.show()

In [ ]:
# Collecting shap values from model

X_test_num = pipe.named_steps['preprocess'].transform(X_test)
X_train_num = pipe.named_steps['preprocess'].transform(X_train)
feature_names = pipe.named_steps['preprocess'].get_feature_names_out()
explainer = shap.Explainer(pipe.named_steps["model"], X_train_num)
shap_values = explainer(X_test_num)

display(shap_values.shape)

In [ ]:
print(feature_names)
print("X_train_num:", X_train_num.shape)
print("X_test_num:", X_test_num.shape)

In [ ]:

shap_summary_plot = shap.summary_plot(shap_values,
                                      X_test_num,
                                      feature_names = feature_names,
                                      show = True
                                     )

print(shap_summary_plot)

In [ ]:
print(shap)

In [ ]:
shap.plots.waterfall(shap_values[266])

In [ ]:
# shap.plots.heatmap(shap_values)

In [ ]:
shap.plots.beeswarm(shap_values.abs, color='shap_red')

In [ ]:
# Creating dataframe for shap values for readability

shap_df = pd.DataFrame(shap_values.values, columns = feature_names)
original_data = pd.DataFrame(shap_values.data, columns = feature_names)


display(original_data)
display(shap_df)

In [ ]:
pipe.predict_proba(X_test)[:, 1] 
predicted_classes = pd.DataFrame({
    "actual": y_test,
    "predicted_prob": pipe.predict_proba(X_test)[:, 1],
    "predicted_class": pipe.predict(X_test)
    
    })
for classes, pred_prob, pred_class in zip(predicted_classes["actual"],predicted_classes["predicted_prob"], predicted_classes["predicted_class"] ):
    print("Actual:",classes, "||", "Pred_Prob", pred_prob, "||","Pred_Class", pred_class)

In [ ]:
correct_message = "This is a correct prediction"
error_message = "This is an incorrect prediction"
correct_predictions = pd.DataFrame({
    "id" : [],
    "actual" : [],
    "prob" : [],
    "predict" : []
})

wrong_predictions = pd.DataFrame({
    "id" : [],
    "actual" : [],
    "prob" : [],
    "predict" : []
})

id = 0
for actual, prob, predict in zip(predicted_classes["actual"], 
                                 predicted_classes["predicted_prob"],
                                 predicted_classes["predicted_class"]):
    if((prob <= 0.5) and (actual == predict)):
        correct_predictions.loc[id] = [id, actual, prob, predict] 
        # print("id:", id, "|", correct_message, "|", "Actual:", actual, "|", "Prob:", np.round(prob, 5), "|", "Predict:", predict)
    elif((prob > 0.5) and (actual == predict)):
        correct_predictions.loc[id] = [id, actual, prob, predict] 
        # print("id:", id, "|", correct_message, "|", "Actual:", actual, "|", "Prob:", np.round(prob, 5), "|", "Predict:", predict)
    else: 
        wrong_predictions.loc[id] = [id, actual, prob, predict]
    id += 1

display(correct_predictions, wrong_predictions)

In [ ]:
print(predicted_classes)

In [ ]:
index = 0
for val in y_test:
    print("Index #:", index, "||", "Value:", val)
    index += 1

In [ ]:
count = 0
for feat in shap_df:
    print("Feature:",feat, "||", "Feature Number:", count)
    count +=1

In [ ]:
# Merging original data with shap values to visualize feature importance

merged_df = shap_df.merge(original_data, how = "left", left_index = True, right_index = True)

In [ ]:
display(merged_df)

In [ ]:
merged_df.columns.unique()

## Comparison of shap values to the data used by the model in prediction
### Categorical Variables: 1.0 is the categorical value given for when the shape or polymer was of that type

In [ ]:
# Shape Fragment

for shap, actual in zip(merged_df['cat__Shape_Fragment_x'], merged_df['cat__Shape_Fragment_y']):
    if actual == 1.0:
        print(shap, actual)

In [ ]:
# Shape Sphere

for shap, actual in zip(merged_df['cat__Shape_Sphere_x'], merged_df['cat__Shape_Sphere_y']):
    if actual == 1.0:
        print(shap, actual)

In [ ]:
# Polymer Polypropylene
for shap, actual in zip(merged_df['cat__Polymer_Polypropylene_x'], merged_df['cat__Polymer_Polypropylene_y']):
    if actual == 1.0:
        print(shap, actual)

In [ ]:
for shap, actual in zip(merged_df['cat__Polymer_Polystyrene_x'], merged_df['cat__Polymer_Polystyrene_y']):
    if actual == 1.0:
        print(shap, actual)

In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize = (6,4))
sns.heatmap(cm, annot = True, fmt = "d", cmap = "Blues", cbar = False)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix for Sklearn Pipeline Model")
plt.show()